#!/bin/bash

VERSION=0.6.6

function abort()
{
  echo " *** ERROR $@"
  exit 1
}

function cleanup()
{
  echo "Finished at $(date -u +%Y-%m-%dT%H:%M:%S%z)"
}

echo "Started at $(date -u +%Y-%m-%dT%H:%M:%S%z)"
trap cleanup EXIT

terraform --version | grep $VERSION > /dev/null 2>&1
if [ $? -ne 0 ]; then
  abort "Could not find terraform version $VERSION"
fi